RestaurauntApp/Controllers/DiscountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RestaurauntApp.DTOS;
using RestaurauntApp.Repositories.Base;

namespace RestaurauntApp.Controllers
{
    [Route("[controller]/[action]")]
    [Authorize(Roles = "Admin")]
    public class DiscountController : Controller
    {
        private readonly IDiscountRepository discountRepository;
        public DiscountController(IDiscountRepository discountRepository)
        {
            this.discountRepository = discountRepository;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(DiscountCodeDTO discountCode)
        {
            if (!ModelState.IsValid)
            {
                return View("Add");
            }

            var result = await discountRepository.AddDiscountCode(discountCode);
            if (result)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Failed to add discount code."); // Добавляем ошибку модели
                return View("Add");
            }
        }

    }
}

RestaurauntApp/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net;
using RestaurauntApp.DTOS;
using RestaurauntApp.Services.Base;
using Microsoft.AspNetCore.Authorization;

namespace RestaurantApp.Controllers
{
    [Route("menu")]
    public class MenuController : Controller
    {
        private readonly IMenuService menuService;
        public MenuController(IMenuService menuService)
        {
            this.menuService = menuService;
        }

        public async Task<IActionResult> GetAll()
        {
            var menuItems = await menuService.GetAllMenuItems();
            return View(menuItems);
        }

        [HttpGet]
        [Route("[action]")]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Create([FromForm][Bind("Id,Name,Description,Category,IsVegetarian,Calories,Price")] MenuItemDTO newMenuItem, IFormFile Image)
        {
            try
            {
                var rowsAffected = await menuService.CreateMenuItem(newMenuItem, Image);

                if (rowsAffected > 0)
                {
                    return RedirectToAction("GetAll");
                }
                else
                {
                    return StatusCode((int)HttpStatusCode.InternalServerError, "Failed to insert the product.");
                }
            }
            catch (Exception)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, "An error occurred while processing the request.");
            }
        }

        [HttpDelete("{id}")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var rowsDeleted = await menuService.DeleteMenuItem(id);
            if (rowsDeleted == 0)
            {
                return NotFound("The product you are trying to delete does not exist.");
            }
            return RedirectToAction("GetAll");

        }

        [HttpGet]
        [Route("GetDetails")]
        public async Task<IActionResult> GetDetails(int id)
        {
            var menuItem = await menuService.GetMenuItem(id);
            return View(menuItem);
        }

        [Authorize(Roles = "Admin")]
        [HttpPut("update/{id}")]
        public async Task<IActionResult> UpdateMenuItemAsync(int id, [FromBody] MenuItemDTO menuItemToUpdate)
        {
            var rowsAffected = await menuService.UpdateMenuItem(id, menuItemToUpdate);
            if (rowsAffected == 0)
            {
                return NotFound("The product you are trying to update does not exist.");
            }
            return Ok();
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        [Route("edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            var menuItem = await menuService.GetMenuItem(id);
            if (menuItem == null)
            {
                return NotFound();
            }
            return View(menuItem);
        }

        [HttpPost]
        [Route("update")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(int id, MenuItemDTO menuItem)
        {
            if (!ModelState.IsValid)
            {
                return View(menuItem);
            }
            var rowsAffected = await menuService.UpdateMenuItem(id, menuItem);
            if (rowsAffected == 0)
            {
                return NotFound();
            }

            return RedirectToAction("GetAll");
        }

    }
}

RestaurauntApp/Controllers/OrderController.cs
using System.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RestaurauntApp.Services.Base;

namespace RestaurauntApp.Controllers
{
    [Route("[controller]/[action]")]
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderService orderService;
        public OrderController(IOrderService orderService)
        {
            this.orderService = orderService;
        }

        [HttpGet]
        public async Task<IActionResult> GetOrders()
        {
            var user = HttpContext.User;
            var orders = await orderService.GetOrders(user);
            return View(orders);
        }

        [HttpGet]
        public async Task<IActionResult> GetCheckoutDetails(int orderId)
        {
            var checkout = await orderService.GetCheckoutDetails(orderId);
            return View(checkout);
        }

        [HttpPost]
        // [HttpGet("UpdateOrderStatus")]
        public async Task<IActionResult> UpdateOrderStatus([FromQuery] int orderId, [FromQuery] string action)
        {
         try
            {
                var result = await orderService.UpdateOrderStatus(orderId, action);
                if (result)
                {
                    return Ok(); // Возвращаем успешный результат
                }
                else
                {
                    return BadRequest(); // Возвращаем ошибку, если действие не выполнено
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return StatusCode(500, "An error occurred while processing the request.");
            }
        }

    }
}

RestaurauntApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - RestaurantApp</title>

<link href="~/css/Menu/GetAll/light.css" rel="stylesheet" type="text/css" data-page="Menu/GetAll" />
<link href="~/css/Menu/Create/light.css" rel="stylesheet" type="text/css" data-page="Menu/Create" />
<link href="~/css/Cart/Checkout/light.css" rel="stylesheet" type="text/css" data-page="Cart/Checkout" />
<link href="~/css/Home/Contacts/light.css" rel="stylesheet" type="text/css" data-page="Home/Contacts/" />
<link href="~/css/Menu/GetAll/light.css" rel="stylesheet" type="text/css" data-page="Menu/GetDetails">
<link href="~/css/Menu/Edit/light.css" rel="stylesheet" type="text/css" data-page="Menu/Edit" />
<link href="~/css/Account/Profile/light.css" rel="stylesheet" type="text/css" data-page="Account/Profile" />
<link href="~/css/Order/GetOrders/light.css" rel="stylesheet" type="text/css" data-page="/Order/GetOrders" />
<link href="~/css/Account/ChangePassword/light.css" rel="stylesheet" type="text/css"  data-page="/Account/ChangePassword" />
<!-- Stylesheets -->
<link href="https://db.onlinewebfonts.com/c/a0faafb86752ddff4c3ec18939c68830?family=Roc+Grotesk+W05+Wide"
    rel="stylesheet">
@RenderSection("Styles", required: false)

<style>
    @@import url(https://db.onlinewebfonts.com/c/a0faafb86752ddff4c3ec18939c68830?family=Roc+Grotesk+W05+Wide);

    .checkbox-wrapper-58 *,
    .checkbox-wrapper-58 ::after,
    .checkbox-wrapper-58 ::before {
        box-sizing: border-box;
    }

    /* The switch - the box around the slider */
    .checkbox-wrapper-58 .switch {
        /* Variables */
        --switch_width: 2em;
        --switch_height: 1em;
        --thumb_color: #e8e8e8;
        --track_color: #e8e8e8;
        --track_active_color: #888;
        --outline_color: #000;
        font-size: 17px;
        position: relative;
        display: inline-block;
        width: var(--switch_width);
        height: var(--switch_height);
    }

    /* The slider */
    .checkbox-wrapper-58 .slider {
        box-sizing: border-box;
        border: 2px solid var(--outline_color);
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: var(--track_color);
        transition: .15s;
        border-radius: var(--switch_height);
    }

    .checkbox-wrapper-58 .slider:before {
        box-sizing: border-box;
        position: absolute;
        content: "";
        height: var(--switch_height);
        width: var(--switch_height);
        border: 2px solid var(--outline_color);
        border-radius: 100%;
        left: -2px;
        bottom: -2px;
        background-color: var(--thumb_color);
        transform: translateY(-0.2em);
        box-shadow: 0 0.2em 0 var(--outline_color);
        transition: .15s;
    }

    .checkbox-wrapper-58 input:checked+.slider {
        background-color: var(--track_active_color);
    }

    .checkbox-wrapper-58 input:focus-visible+.slider {
        box-shadow: 0 0 0 2px var(--track_active_color);
    }

    /* Raise thumb when hovered */
    .checkbox-wrapper-58 input:hover+.slider:before {
        transform: translateY(-0.3em);
        box-shadow: 0 0.3em 0 var(--outline_color);
    }

    .checkbox-wrapper-58 input:checked+.slider:before {
        transform: translateX(calc(var(--switch_width) - var(--switch_height))) translateY(-0.2em);
    }

    /* Raise thumb when hovered & checked */
    .checkbox-wrapper-58 input:hover:checked+.slider:before {
        transform: translateX(calc(var(--switch_width) - var(--switch_height))) translateY(-0.3em);
        box-shadow: 0 0.3em 0 var(--outline_color);
    }

    body,
    h1,
    h2,
    h3,
    p,
    ul,
    li {
        margin: 0;
        padding: 0;
    }

    body {
        min-width: 500px;
        background-color: #000000;
    }

    body {
        font-family: "Roc Grotesk W05 Wide", sans-serif;
        font-style: normal;
        font-weight: 400;
        font-size: 14px;
        line-height: 14px;
        background-color: #f2f2f2;
        color: #333;
        min-height: 100vh;
        margin: 0;
        display: grid;
        grid-template-rows: auto 1fr auto;
    }

    header {
        background-color: #080708;
        color: white;
        text-align: center;
        padding: 1em;
        min-height: 50px;
    }

    .sticky-header {
        position: sticky;
        top: 0;
        background-color: #080708;
        color: white;
        text-align: center;
        padding: 1.5em;
        z-index: 100;
        box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.2);
        min-height: 50px;
    }

    nav a {
        color: white;
        text-decoration: none;
        padding: 0.5em 0.5em;
        border-radius: 5px;
        font-weight: bold;
        text-transform: uppercase;
        font-size: 22px;
    }

    nav a:not(.logo-link):hover {
        color: yellow;
        background-color: #080708;
        transition: 0.3s;
        cursor: pointer;
        box-shadow: 0px 0px 10px yellow;
    }

    .logo-link {
        align-items: center;
    }

    .logo-image {
        margin-right: 10px;
        vertical-align: middle;
    }

    .logo-text {
        vertical-align: middle;
    }

    footer {
        background-color: #080708;
        color: white;
        text-align: center;
        padding: 1em;
        margin-top: auto;
    }

    .page-container {
        display: flex;
        flex-direction: column;
        min-height: 90vh;
    }


    @@media (max-width: 768px) {

        body {
            font-size: 12px;
        }

        nav a {
            font-size: 18px;
        }

        .logo-link {
            flex-direction: column;
            align-items: center;
        }

        .logo-image {
            margin-right: 0;
            margin-bottom: 5px;
        }

        .logo-text {
            font-size: 16px;
        }

        nav {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        nav a:not(.logo-link) {
            margin: 5px 0;
        }
    }

    .header-content {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .logo-link,
    nav a {
        margin: 5px 0;
    }
</style>

<body>
    <div class="page-container">
        <header class="sticky-header">
            <nav>
                <div class="header-content">
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="logo-link">
                        <img src="@Url.Content("~/Assets/icon.png")" alt="Pizza Haven Logo" width="50" height="50"
                            class="logo-image">
                        <span class="logo-text">Pizza Haven</span>
                    </a>
                    <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    <a asp-area="" asp-controller="Menu" asp-action="GetAll">Menu</a>
                    @if (this.User.IsInRole("Admin"))
                    {
                        <a asp-area="" asp-controller="Menu" asp-action="Create">Create menu item</a>
                        <a asp-area="" asp-controller="Discount" asp-action="Add">Add discount code</a>
                    }
                    @if (this.User?.Identity?.IsAuthenticated == false)
                    {
                        <a asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        <a asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                    }
                    @if (this.User?.Identity?.IsAuthenticated == true)

                    {
                        <a asp-area="" asp-controller="Cart" asp-action="Cart">Cart</a>
                        <a asp-area="" asp-controller="Order" asp-action="GetOrders">Orders</a>
                        <a asp-area="" asp-controller="Account" asp-action="Profile">Profile</a>

                    }
                    <a asp-area="" asp-controller="Home" asp-action="Contacts">Contacts</a>
                    @if (this.User?.Identity?.IsAuthenticated == true)
                    {
                        <a asp-area="" asp-controller="Account" asp-action="LogOut">Logout</a>
                    }
                    <div class="checkbox-wrapper-58">
                        <label class="switch">
                            <input id="check-5" type="checkbox" onclick="toggleTheme()">
                            <span class="slider"></span>
                        </label>
                    </div>
                </div>
            </nav>
        </header>


        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        @await RenderSectionAsync("Scripts", required: false)
    </div>
</body>

<footer>
    <p>&copy; 2024 Pizza Haven. All rights reserved.</p>
</footer>

</html>
<script>
    function toggleTheme() {
        var checkbox = document.getElementById('check-5');
        var isChecked = checkbox.checked;

        if (isChecked) {
            changeTheme('dark');
        } else {
            changeTheme('light');
        }
        localStorage.setItem('themeCheckbox', isChecked);
    }

    function changeTheme(theme) {
        var styleSheetName = theme === 'dark' ? 'dark.css' : 'light.css';

        // Получаем ссылки на все элементы <link>, подключающие стили для страницы
        var allPageStyles = document.querySelectorAll('link[rel="stylesheet"][type="text/css"]');

        // Перебираем все найденные элементы <link> и меняем их href на новый путь к CSS файлу
        allPageStyles.forEach(function (style) {
            var oldPath = style.getAttribute('href'); // Получаем текущий путь к CSS файлу
            var basePath = oldPath.split('/').slice(0, -1).join('/') + '/'; // Получаем начальный путь к CSS файлу
            var newPath = basePath + styleSheetName; // Формируем новый путь к CSS файлу
            style.href = newPath; // Устанавливаем новый путь к CSS файлу
        });

        // Сохраняем выбранную тему в cookie
        document.cookie = "theme=" + theme + ";path=/";
    }

    // Функция для чтения значения cookie
    function getCookie(name) {
        var value = "; " + document.cookie;
        var parts = value.split("; " + name + "=");
        if (parts.length === 2) return parts.pop().split(";").shift();
    }

    // При загрузке страницы применяем сохраненную тему (если она есть)
    window.onload = function () {
        var isChecked = localStorage.getItem('themeCheckbox');
        if (isChecked === 'true') {
            // Если чекбокс был отмечен, устанавливаем его состояние
            document.getElementById('check-5').checked = true;
        }
        var savedTheme = getCookie("theme");
        if (savedTheme) {
            changeTheme(savedTheme);
        }
    };



</script>